
FRAME_HEIGHT = 256
FRAME_WIDTH = 256
FRAME_CENTER = int(FRAME_WIDTH / 2)


ROAD_DETECT_VERTICAL = FRAME_CENTER
ROAD_DETECT_VERTICAL_RIGHT = FRAME_CENTER + 30
ROAD_DETECT_VERTICAL_LEFT = FRAME_CENTER - 30
ROAD_DETECT_HORIZON = FRAME_HEIGHT - int(FRAME_HEIGHT/3)


BOUNDARY_DETECT_VERTICAL = FRAME_CENTER
BOUNDARY_DETECT_VERTICAL_RIGHT = FRAME_CENTER + 40
BOUNDARY_DETECT_VERTICAL_LEFT = FRAME_CENTER - 40
BOUNDARY_DETECT_HORIZON = FRAME_HEIGHT - 10


FINISHLINE_DETECT_HORIZON = FRAME_HEIGHT - int(FRAME_HEIGHT/4)

# represent distance between obstancle and car
# OBSTANCLE_DETECT_HORIZON = FRAME_HEIGHT - int(FRAME_HEIGHT/2) + 10


OBSTANCLE_DETECT_HORIZON = FRAME_HEIGHT - int(FRAME_HEIGHT/4)